### ISSUE TITLE
Refugee Town v0.4

### ISSUE THREAD

**Issue by luk3ZPL** [vcmi/vcmi-mods-repository#12]
"vcmi": {
  "name" : "Refugee Town v0.4", 
	"description" : "updated to VCMI 1.1",
	"version" : "0.4",
	"author" : "[Yuya](https://forum.vcmi.eu/u/Yuya)",
	"contact" : "https://forum.vcmi.eu/t/new-town-mod-refugee/5002",
	"modType" : "Town",
  "screenshots":
  [
	  "https://forum.vcmi.eu/uploads/default/original/2X/8/801e03d457a73e483c1f66561406299c68544ca7.jpeg"
	],
  "changelog" :
	{
		"0.4" : [ "Latest release" ]
	},
	"download": "https://github.com/luk3ZPL/VCMI-mods/blob/main/%5BTown%5D%20RefugeeTown%20(v0.4%20updated%20to%20VCMI%201.1).7z"	
},

**Comment by misiokles** [comment]
Mod added to launcher with other way.
