### ISSUE TITLE
Durotar town mod

### ISSUE THREAD

**Issue by vdhan** [vcmi/vcmi-mods-repository#33]
"vcmi": {
  "name": "Durotar",
  "description": "Durotar town",
  "version": "1.1.0",
  "author": "Vũ Đắc Hoàng Ân",
  "contact": "https://vudachoangan.com/",
  "modType": "Town",
  "download": "https://github.com/vdhan/durotar/archive/refs/heads/main.zip"
}

**Comment by misiokles** [comment]
We decided not to add mods to repository from external sources. This mod (Horde in original) contains graphics rather poor quality. I'm thinking about additional repo with various more or less good mods ry (like Foundry or Swarm)

**Comment by vdhan** [comment]
> We decided not to add mods to repository from external sources. This mod (Horde in original) contains graphics rather poor quality.

Could you please give me some examples? They may be fixed in this new version.
