### ISSUE TITLE
There is a problem with polish translation of Haven town

### ISSUE THREAD

**Issue by pppbb** [vcmi/vcmi-mods-repository#41]
Don't know how to contact author.

**Comment by misiokles** [comment]
You can reach Dru, by describe problem here: https://www.forum.acidcave.net/topic.php?TID=890&pid=166758&page=129

**Comment by pppbb** [comment]
> You can reach Dru, by describe problem here: https://www.forum.acidcave.net/topic.php?TID=890&pid=166758&page=129

Thanks
