### ISSUE TITLE
new mod

### ISSUE THREAD

**Issue by DoRFirePaladin** [vcmi/vcmi-mods-repository#44]
"flugels": {
  "name" : "Flugels - New Neutral Creature", 
	"description" : "A new neutral creature based on No Game No Life's Flugel race. Also my first H3 creature ever. Credit for the model goes to codealdnoah.",
	"version" : "0.9.0",
	"author" : "Fire Paladin",
	"contact" : "amurgul@protonmail.com",
	"modType" : "Creatures",
  "screenshots":
  [
	  "https://github.com/DoRFirePaladin/flugel-creature/blob/2c33c2b0b452f17e4eda1c39ff73e24f926899dd/screenshots/Screen1.png",
	  "https://github.com/DoRFirePaladin/flugel-creature/blob/2c33c2b0b452f17e4eda1c39ff73e24f926899dd/screenshots/Screen2.png",
	  "https://github.com/DoRFirePaladin/flugel-creature/blob/2c33c2b0b452f17e4eda1c39ff73e24f926899dd/screenshots/Screen3.png"
	],
	"download": "https://github.com/DoRFirePaladin/flugel-creature/archive/refs/heads/master.zip"	
},

**Comment by misiokles** [comment]
Forked and added to repository
