### ISSUE TITLE
Graphical update - Heavenly Forge 2000 creatures

### ISSUE THREAD

**Issue by Aph-ra** [vcmi/vcmi-mods-repository#48]
I am not the author of this mod (it says HOMM Modding Community in mod.json) but I noticed 2 of the icons were compressed bmps, so I remade them in png format with the correct background.

Content is found in ...\forge2kedit\Content\Sprites\forge2k\iconsBig

![CPrL197B](https://github.com/vcmi/vcmi-mods-repository/assets/148544465/34bf0d04-8c67-4981-9f79-b64f7dd71efc)
![CPrL206B-v1](https://github.com/vcmi/vcmi-mods-repository/assets/148544465/7900ea71-2465-45a3-9322-a8e8f9d43030)
![CPrL206B-v2](https://github.com/vcmi/vcmi-mods-repository/assets/148544465/870111f9-ec18-4d8a-aea7-24db062f506b)

**Comment by misiokles** [comment]
Uploaded in 2.3.3 version (available for vcmi-1.5)
