### ISSUE TITLE
Graphical update - H3 Themes

### ISSUE THREAD

**Issue by Aph-ra** [vcmi/vcmi-mods-repository#51]
Icons are now updated to the latest HotA icons. HotA 1.7 theme added; HotA 1.6 and 1.7 themes are separate themes.

https://drive.google.com/file/d/1F16pzg-4q-4_oEGCtRweQOHrbwcisuLY/view?usp=drive_link

**Comment by Aph-ra** [comment]
Updated to 1.4. Added WoG theme.
https://drive.google.com/file/d/1Orkq9WRUZmGs87aE_3L5TaoMlxSgk180/view?usp=drive_link

**Comment by Aph-ra** [comment]
Updated to 1.5.0. Added ToW theme.
https://drive.google.com/file/d/1VlZ3ZKAWkGmErqziG8LtPixO9MpXZI1H/view?usp=drive_link

**Comment by Aph-ra** [comment]
Updated to 1.6.0. Added Complete theme.
https://drive.google.com/file/d/1PENODa-kpfxTG8Fhkm_TdkAl1cUlYh3y/view?usp=sharing

**Comment by Aph-ra** [comment]
Updated to 1.7.0. Added VCMI theme; minor graphical fixes.
https://drive.google.com/file/d/1crRkR29pDzXKbk6h4ADd1hguvKXY1N-a/view?usp=sharing

**Comment by Aph-ra** [comment]
Updated to 1.7.1. Minor code fixes.
https://drive.google.com/file/d/1ZVx0DfGjATepalhsPvdpIXzfSwPPBqfY/view?usp=sharing

**Comment by Aph-ra** [comment]
Updated to 1.7.2. WoG menu conflict updated with new folder name.
https://drive.google.com/file/d/1P3UZQVZI24HGlOKg8FNyKjZ-Iwttv7ZH/view?usp=sharing

**Comment by Aph-ra** [comment]
Updated to 1.8.0. Added HD theme.
https://drive.google.com/file/d/1EOXC-NYtxLut5IJxbZYY-w-3kW5T9ei2/view?usp=sharing

**Comment by misiokles** [comment]
Uploaded to repository
