### ISSUE TITLE
Mod - New Old Heroes

### ISSUE THREAD

**Issue by Aph-ra** [vcmi/vcmi-mods-repository#53]
New heroes based on old 3DO artwork. Requires Horn of the Abyss.

[new-old-heroes-v1.0.zip](https://github.com/vcmi/vcmi-mods-repository/files/15424959/new-old-heroes-v1.0.zip)

**Comment by Aph-ra** [comment]
Updated to 1.1.0: added Nicolas and Kastore

[new-old-heroes-v1.1.0-vcmi.zip](https://github.com/vcmi/vcmi-mods-repository/files/15439164/new-old-heroes-v1.1.0-vcmi.zip)

**Comment by Aph-ra** [comment]
Updated to 1.1.1: bug fixes (added some commas)

[new-old-heroes-v1.1.1-vcmi.zip](https://github.com/vcmi/vcmi-mods-repository/files/15444202/new-old-heroes-v1.1.1-vcmi.zip)

**Comment by Aph-ra** [comment]
Updated to 1.2.0: Added some HotA portrait-only campaign heroes

[new-old-heroes-v1.2.0-vcmi.zip](https://github.com/user-attachments/files/15569879/new-old-heroes-v1.2.0-vcmi.zip)

**Comment by Aph-ra** [comment]
Updated to 1.3.0: Athe now has a Spell Book & starts with Fireball; Added Lord Soth from WoG (totally not originally from Dragonlance/Ravenloft)
[new-old-heroes-v1.3.0-vcmi.zip](https://github.com/user-attachments/files/16482782/new-old-heroes-v1.3.0-vcmi.zip)

**Comment by misiokles** [comment]
Uploaded to repository
