### ISSUE TITLE
vcmi-1.6 errors

### ISSUE THREAD

**Issue by pppbb** [vcmi/vcmi-mods-repository#63]
After refreshing repository:

> /home/piotr/.cache/vcmi/downloads/refugee-town.json is not valid JSON!
> At line 13, position 22 warning: Duplicate element encountered!
> /home/piotr/.cache/vcmi/downloads/undead-sphinxes.json is not valid JSON!
At line 36, position 4 warning: Comma expected!
At line 36, position 4 error: Value expected!
At line 36, position 4 warning: Not all file was parsed!

**Comment by misiokles** [comment]
Fixed
