### ISSUE TITLE
an-expansion

### ISSUE THREAD

**Issue by vdhan** [vcmi/vcmi-mods-repository#9]
"vcmi": {
  "name": "an-expansion",
  "description": "Rebalances skills, heroes, creatures, etc.",
  "version": "3.0.0",
  "author": "Vũ Đắc Hoàng Ân",
  "contact": "https://vudachoangan.com",
  "modType": "Expansion",
  "download": "https://github.com/vdhan/an-expansion/archive/refs/heads/master.zip"
}

**Comment by misiokles** [comment]
Mod was added to launcher.
